#!/bin/sh
echo 68 > /sys/class/gpio/export
echo 69 > /sys/class/gpio/export
echo 70 > /sys/class/gpio/export
echo 71 > /sys/class/gpio/export
echo 76 > /sys/class/gpio/export
echo 77 > /sys/class/gpio/export
echo 78 > /sys/class/gpio/export
echo 79 > /sys/class/gpio/export

echo 103 > /sys/class/gpio/export

echo 111 > /sys/class/gpio/export
echo 123 > /sys/class/gpio/export

echo out > /sys/class/gpio/gpio68/direction
echo out > /sys/class/gpio/gpio69/direction
echo out > /sys/class/gpio/gpio70/direction
echo out > /sys/class/gpio/gpio71/direction

echo out > /sys/class/gpio/gpio76/direction
echo out > /sys/class/gpio/gpio77/direction
echo out > /sys/class/gpio/gpio78/direction
echo out > /sys/class/gpio/gpio79/direction

echo out > /sys/class/gpio/gpio103/direction

echo in > /sys/class/gpio/gpio111/direction
echo in > /sys/class/gpio/gpio123/direction

echo 0 > /sys/class/gpio/gpio68/value
echo 0 > /sys/class/gpio/gpio69/value
echo 0 > /sys/class/gpio/gpio70/value
echo 0 > /sys/class/gpio/gpio71/value

echo 0 > /sys/class/gpio/gpio76/value
echo 0 > /sys/class/gpio/gpio77/value
echo 0 > /sys/class/gpio/gpio78/value
echo 0 > /sys/class/gpio/gpio79/value
echo 0 > /sys/class/gpio/gpio103/value

#/opt/m287net & >/dev/null

